"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
"""

n0 = 1
n1 = 2
not_exceed = 4_000_000
even_fibsum = 0


while n1 <= not_exceed:
    #print(n1, n0)
    if n1 % 2 == 0:
        even_fibsum += n1

    tmp_n0 = n0
    n0 = n1
    n1 = tmp_n0 + n1


print(even_fibsum) 
